version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "${NEO4J_PORT_HTTP}:7474" # HTTP
      - "${NEO4J_PORT_BOLT}:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_default__database=${NEO4J_DEFAULT_DATABASE}
      - NEO4JLABS_PLUGINS=["graph-data-science"] # Enable GDS Plugin
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes       # Accept the license
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
